import '@/styles/globals.css'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'
import Head from 'next/head'
import Cookies from 'js-cookie'
import { useEffect } from 'react'

export default function App({ Component, pageProps }) {
  
  const isAuth = Cookies.get('auth') === 'true' ? true: false;
  const login = Cookies.get('_ln');
  const password = Cookies.get('_pd');

  async function loginin() {
    const response = await fetch('/api/login', {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({login, password})
    })
    if(response.ok) {
      console.log('Logged in as ' + login + '. Password: ' + password);
    } else
      console.log(response.status);
  }


  if (isAuth) loginin();

  return (
  <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isAuth = {isAuth} login = {login}/>
      <Component {...pageProps} isAuth = {isAuth} />
      <Footer/>
    </>
  )
}
